### ISSUE TITLE
Review Youtube terms

### ISSUE THREAD

**Issue by santarabantoosoo** [santarabantoosoo/Blogs#3]
terms 

money (feasibility)

**Comment by santarabantoosoo** [comment]
trial

**Comment by Alshareef-Aly** [comment]
###  [YouTube Partner Program (YPP)](https://support.google.com/youtube/answer/72851#zippy=%2Cwhat-does-valid-public-watch-hours-mean%2Cwhat-happens-if-my-counts-drop-below-the-threshold-after-i-apply%2Cim-no-longer-in-ypp-or-i-was-never-in-the-program-and-im-seeing-ads-on-my-videos-am-i-earning-revenue-from-those-ads)

**[How to make money on YouTube](https://support.google.com/youtube/answer/72857?hl=en#:~:text=You%20can%20make%20money%20on,special%20perks%20that%20you%20offer.)**

- [ ] Follow all the [YouTube channel monetization policies](https://support.google.com/youtube/answer/1311392).
- [ ] Have no active [Community Guidelines strikes](https://support.google.com/youtube/answer/2802032) on your channel.
- [ ] Have more than 4,000 valid public watch hours in the last 12 months.
- [ ] Have more than 1,000 subscribers.
- [ ] Have a linked AdSense account.
- [ ] Get reviewed. (typically about 1 month after we meet the threshold).

[**Monetization options**](https://support.google.com/youtube/answer/11912533)

- [ ] [Advertising revenue](https://support.google.com/youtube/answer/9314357)
- [ ] [Channel memberships](https://support.google.com/youtube/answer/7636690)
- [ ] [Merch](https://support.google.com/youtube/answer/9454088)
- [ ] [Super Thanks, Super Chat & Super Stickers](https://support.google.com/youtube/answer/7288782)
- [ ] [YouTube Premium Revenue](https://support.google.com/youtube/answer/6306276#YouTube_Red_revenue_1)

### [YouTube Shorts](https://support.google.com/youtube/answer/10923658#eligibility)

- 100$ ~ 10,000$ Monthly bonus

**Comment by Alshareef-Aly** [comment]
#8

**Comment by santarabantoosoo** [comment]
awesome 

bas ana msh fahem 7aga :)
